import React from "react";
import "./reportPreview.css";

export default function ReportView({ data }: any) {
  if (!data) return null;

  return (
    <div style={{ background: "#f3f3f3", padding: "30px" }}>
      <div className="report">

        <div className="report-card">

          {/* HEADER */}
          <div className="report-header">
            <div style={{ display: "flex", justifyContent: "space-between" }}>
              <div>
                <h2>{data.user.name}'s Learning Report</h2>
                <p>
                  {new Date(data.generatedAt).toDateString()}
                </p>
                <span className="badge">Generated by Edunex</span>
              </div>

              <div style={{ textAlign: "right" }}>
                <div style={{ fontSize: "28px" }}>
                  {data.stats.avgScore}%
                </div>
                <div style={{ fontSize: "12px" }}>Overall score</div>
              </div>
            </div>
          </div>

          {/* METRICS */}
          <div className="section">
            <h4>THIS MONTH</h4>

            <div className="metrics">
              <Metric v={data.stats.totalHours + "h"} l="Study hours" />
              <Metric v={data.stats.quizzesCompleted} l="Quizzes done" />
              <Metric v={data.stats.flashcardsReviewed} l="Flashcards" />
              <Metric v={data.stats.summariesCreated} l="Summaries" />
            </div>
          </div>

          {/* SUBJECT */}
          <div className="section">
            <h4>SUBJECT BREAKDOWN</h4>

            {data.subjectDistribution.map((s: any, i: number) => (
              <div key={i} style={{ marginBottom: "8px" }}>
                <div style={{ display: "flex", justifyContent: "space-between" }}>
                  <span>{s.subject}</span>
                  <span>{s.value * 10}%</span>
                </div>

                <div className="bar-track">
                  <div
                    className="bar-fill"
                    style={{
                      width: `${s.value * 10}%`,
                      background: "#7F77DD",
                    }}
                  />
                </div>
              </div>
            ))}
          </div>

          {/* QUIZ TABLE */}
          <div className="section">
            <h4>RECENT QUIZ ATTEMPTS</h4>

            <div className="quiz-header">
              <span>Quiz</span>
              <span>Subject</span>
              <span>Score</span>
              <span>Date</span>
            </div>

            {data.recentQuizzes.map((q: any, i: number) => (
              <div key={i} className="quiz-row">
                <span>{q.quizName}</span>
                <span>{q.subject}</span>

                <span className={
                  q.score > 80 ? "score-pill score-high" :
                  q.score > 50 ? "score-pill score-mid" :
                  "score-pill score-low"
                }>
                  {q.score}%
                </span>

                <span>
                  {new Date(q.createdAt).toLocaleDateString()}
                </span>
              </div>
            ))}
          </div>

          {/* SUMMARIES */}
          <div className="section">
            <h4>SUMMARIES CREATED</h4>

            {data.recentSummaries.map((s: any, i: number) => (
              <div key={i} style={{
                display: "flex",
                justifyContent: "space-between"
              }}>
                <span>{s.title}</span>
                <span>{s.subject}</span>
              </div>
            ))}
          </div>

          {/* INSIGHTS */}
          <div className="section">
            <h4>AI INSIGHTS</h4>

            {data.insights.map((i: any, idx: number) => (
              <div key={idx} className="insight-row">
                <span>💡</span>
                <div>{i}</div>
              </div>
            ))}
          </div>

          {/* STREAK */}
          <div className="section">
            <h4>STUDY STREAK</h4>

            <div className="streak-num">
              {data.streak} days
            </div>
          </div>

          {/* SHARE */}
          <div className="section">
            <h4>SHARE YOUR PROGRESS</h4>

            <div style={{ display: "flex", gap: "10px" }}>
              <button>Instagram</button>
              <button>WhatsApp</button>
              <button>Twitter</button>
              <button>LinkedIn</button>
              <button style={{ background: "#534AB7", color: "#fff" }}>
                Download PDF
              </button>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}

function Metric({ v, l }: any) {
  return (
    <div className="metric">
      <div style={{ fontSize: "20px", fontWeight: "600" }}>{v}</div>
      <div style={{ fontSize: "12px" }}>{l}</div>
    </div>
  );
}