import React from "react";
import "./reportPreview.css";

export default function ReportView({ data }: any) {
  if (!data) return null;

  return (
    <div style={{ background: "#f5f6fa", padding: "40px 0", minHeight: "100vh" }}>
      <div className="report">
        <div className="report-card">

          {/* HEADER */}
          <div className="report-header">
            <div>
              <h1>{data.user?.name || "Aryan"}'s Learning Report</h1>
              <p>
                {new Date(data.generatedAt).toDateString()}
              </p>
              <span className="badge">Generated by Edunex</span>
            </div>

            <div className="score-box">
              <h1>{data.stats?.avgScore || 72}%</h1>
              <p>Overall score</p>
            </div>
          </div>

          {/* METRICS */}
          <div className="section">
            <h4 className="section-title">THIS MONTH</h4>

            <div className="metrics">
              <Metric v={(data.stats?.totalHours || 5.6) + "h"} l="Study hours" />
              <Metric v={data.stats?.quizzesCompleted || 14} l="Quizzes done" />
              <Metric v={data.stats?.flashcardsReviewed || 48} l="Flashcards" />
              <Metric v={data.stats?.summariesCreated || 6} l="Summaries" />
            </div>
          </div>

          {/* SUBJECT */}
          <div className="section">
            <h4 className="section-title">SUBJECT BREAKDOWN</h4>

            {(data.subjectDistribution || []).map((s: any, i: number) => (
              <div key={i}>
                <div className="subject-row">
                  <span>{s.subject}</span>
                  <span>{s.value * 10}%</span>
                </div>

                <div className="bar-track">
                  <div
                    className={`bar-fill ${s.subject.toLowerCase()}`}
                    style={{ width: `${s.value * 10}%` }}
                  />
                </div>
              </div>
            ))}
          </div>

          {/* QUIZ TABLE */}
          <div className="section">
            <h4 className="section-title">RECENT QUIZ ATTEMPTS</h4>

            <div className="quiz-header">
              <span>Quiz</span>
              <span>Subject</span>
              <span>Score</span>
              <span>Date</span>
            </div>

            {(data.recentQuizzes || []).map((q: any, i: number) => (
              <div key={i} className="quiz-row">
                <span>{q.title || q.quizName}</span>
                <span>{q.subject}</span>

                <span className={
                  q.score > 80 ? "score-pill score-high" :
                  q.score > 50 ? "score-pill score-mid" :
                  "score-pill score-low"
                }>
                  {q.score}%
                </span>

                <span>
                  {new Date(q.createdAt || Date.now()).toLocaleDateString()}
                </span>
              </div>
            ))}
          </div>

          {/* SUMMARIES */}
          <div className="section">
            <h4 className="section-title">SUMMARIES CREATED</h4>

            {(data.recentSummaries || []).map((s: any, i: number) => (
              <div key={i} className="quiz-row">
                <span>{s.title}</span>
                <span>{s.subject}</span>
                <span></span>
                <span></span>
              </div>
            ))}
          </div>

          {/* INSIGHTS */}
          <div className="section">
            <h4 className="section-title">AI INSIGHTS</h4>

            {(data.insights || [
              "Strong in Newton's Laws — scored 92%",
              "Probability needs attention — 41%",
              "Consistency improving — keep it up!"
            ]).map((i: any, idx: number) => (
              <div key={idx} className="insight-row">
                <div className="insight-icon">💡</div>
                <div className="insight-text">{i}</div>
              </div>
            ))}
          </div>

          {/* STREAK */}
          <div className="section">
            <h4 className="section-title">STUDY STREAK</h4>

            <div className="streak-box">
              <div className="streak-num">{data.streak || 14}</div>
              <div>
                <div className="streak-label">days</div>
                <div className="streak-label">Best: 21 days</div>
              </div>
            </div>
          </div>

          {/* SHARE */}
          <div className="section">
            <h4 className="section-title">SHARE YOUR PROGRESS</h4>

            <div className="share-links">
              <span>Instagram</span>
              <span>WhatsApp</span>
              <span>Twitter</span>
              <span>LinkedIn</span>

              <button className="btn btn-primary">
                Download PDF
              </button>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}

function Metric({ v, l }: any) {
  return (
    <div className="metric">
      <h2>{v}</h2>
      <p>{l}</p>
    </div>
  );
}